package com.example.nicechicken.payment.controller;

import com.example.nicechicken.payment.service.PaymentService;
import com.stripe.exception.StripeException;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/payments")
@RequiredArgsConstructor
public class PaymentController {

    private final PaymentService paymentService;

    @PostMapping("/checkout/{orderId}")
    public ResponseEntity<Map<String, String>> createCheckout(@PathVariable UUID orderId) throws StripeException {
        // Retrieve Stripe payment URL generated by the service
        String checkoutUrl = paymentService.createCheckoutSession(orderId);
        
        // Respond with JSON for easy client parsing
        return ResponseEntity.ok(Map.of("checkoutUrl", checkoutUrl));
    }
}